<?php
// REVISED: Force strict mode and use_only_cookies so PHP rejects session ID's
//          not generated by the server, helping prevent session hijacking.
ini_set('session.use_strict_mode', 1);
ini_set('session.use_only_cookies', 1);
// REVISED: Added cookie protection settings to make cookies harder to steal. 
session_set_cookie_params([
    'httponly' => true,
    'secure'   => true,
    'samesite' => 'Lax'
]);

// Initialize the session.
session_start();

// Check if the user is already logged in. If yes, then redirect them to the welcome page.
// $_SESSION is a superglobal variable built into PHP that contains session variables
// available to the current script. The "loggedin" session variable is true if the user
// is logged in. The built in isset function is used to determine if a variable is declared 
// and is different than NULL. It is used here to make sure that the loggedin variable is 
// set to anything at all.
if(isset($_SESSION["loggedin"]) && $_SESSION["loggedin"] === true){
    header("location: welcome.php");
    exit;
}

// Include config file.
require_once "config.php";

// Define variables and initialize with empty strings.
$username = $password = "";
$username_err = $password_err = "";

// Processing form data when form is submitted.
// $_SERVER is an array containing information such as headers, paths, and script 
// locations. The entries in this array are created by the web server.
// $_SERVER, $_POST, and similarly styled variables are superglobal variables
// in PHP. Unlike normal variables that you assign yourself, PHP has some built-in 
// variables that are always available in your script and in all scopes. These are 
// called Superglobals (awesome name right?) and are predefined in PHP.
// https://teamtreehouse.com/community/why-post-is-all-with-capital-letters
if($_SERVER["REQUEST_METHOD"] == "POST"){

    // Set variables to the values entered by the user and available to the script
    // for later insertion into the SQL statement below.
    $user = $_POST['username'];
    $pass = $_POST['password'];

    // REVISED: Updated SQL query to parametize inputs and block SQL injection
    // REVISED: 2nd update, added password hashing so we need to verify password
    //          via php instead of directly quering the DB.
    $stmt = $link->prepare(
        "SELECT * FROM users_table WHERE username = ?"
    );
    $stmt -> bind_param("ss", $user, $pass);
    $stmt -> execute();

    // Updated result to match above code execution
	$res = $stmt->get_result();

    // The built-in mysqli_stmt_num_rows function accepts a statement 
    // object as a parameter and returns the number of rows in the 
    // result set of the given statement.
    // https://www.tutorialspoint.com/php/php_function_mysqli_stmt_num_rows.htm
    // If the result of the executed SQL statement contains a row,
    // we know that the username and password exists and we can log the user in.

    // REVISED: Forces new session ID on each login to help prevent session hijacking.
    // REVISED: 2nd update, added password hashing so need to verify password in this
    //          stage rather than from our direct DB query earlier.
    if($res->num_rows===1)
        {
        $row = $res->fetch_assoc();

        if(password_verify($pass, $row["password"])) {
            // Give the authenticated user a fresh session ID.
            session_regenerate_id(true);

            $_SESSION["loggedin"] = true;
            $_SESSION["id"] = $row["id"];
            $_SESSION["username"] = $row["username"];

            header("location: welcome.php");
            exit;
        }
    }

    // Either the username doesn't exist or the password didn't match.
    $password_err = "The username and/or the password you entered was not valid."

    // Close connection.
    mysqli_close($link);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
    <style type="text/css">
        body{ font: 14px sans-serif; }
        .wrapper{ width: 350px; padding: 20px; }
    </style>
</head>
<body>
    <div class="wrapper">
        <h1>Welcome to OnePhoto!</h1>
        <h2>Login</h2>
        <p>Please fill in your credentials to login.</p>
        <!-- htmlspecialchars is a built-in PHP function to convert special characters to HTML entities.
        $_SERVER is an array built into PHP containing information such as headers, paths, and script 
        locations. The entries in this array are created by the web server. With $_SERVER["PHP_SELF"] we
        are echoing the complete path, including all parameters, to our site. PHP_SELF is a variable that 
        returns the name and path of the current file (from the root folder). However, without htmlspcialchars 
        we would have an XSS vulnerability (see https://www.webadminblog.com/index.php/2010/02/23/a-xss-vulnerability-in-almost-every-php-form-ive-ever-written/).
        Various errors related to the user-entered strings (or omissions of those) are echoed to the
        output of the form for the user to see. -->
        <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
            <div class="form-group <?php echo (!empty($username_err)) ? 'has-error' : ''; ?>">
                <label>Username</label>
                <input type="text" name="username" class="form-control" value="<?php echo $username; ?>">
                <span class="help-block"><?php echo $username_err; ?></span>
            </div>
            <div class="form-group <?php echo (!empty($password_err)) ? 'has-error' : ''; ?>">
                <label>Password</label>
                <input type="password" name="password" class="form-control">
                <span class="help-block"><?php echo $password_err; ?></span>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Login">
            </div>
            <p>Don't have an account? <a href="index.php">Sign up now</a>.</p>
        </form>
    </div>
</body>
</html>
